dgs: cleanDGS compileDGS runDGS

centro: cleanCentro compileCentro runCentro

utente: cleanUtente compileUtente runUtente

compileDGS:
	cd DGS && gradle build
	
compileCentro:
	cd Centro_de_Vacinacao && gradle build

compileUtente:
	cd Utente && gradle build

runDGS:
	cd DGS && gradle bootRun

runCentro:
	cd Centro_de_Vacinacao && gradle bootRun

runUtente:
	cd Utente && gradle bootRun

cleanDGS:
	cd DGS && gradle clean

cleanCentro:
	cd Centro_de_Vacinacao && gradle clean

cleanUtente:
	cd Utente && gradle clean

